#define KC_GPM_LIKE_SONG C(S(KC_UP))
#define KC_MAC_SHOW_WINS LCTL(KC_UP)

#define MG_HOME_L KC_LCTRL, LT(2,KC_A), LGUI_T(KC_S), LALT_T(KC_D), LCTL_T(KC_F), LSFT_T(KC_G)
#define MG_HOME_R RSFT_T(KC_H), RCTL_T(KC_J), RALT_T(KC_K), RGUI_T(KC_L), LT(1,KC_SCLN), KC_QUOTE
